version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: logger